### ISSUE TITLE
[Feature] Assertions for checking that a collection contains an expected item

### ISSUE THREAD

**Issue by ghost** [maxdeviant/startest#2]
Hello there!

I started using Startest since I like the API decisions being made, and the error reporting is well done.

By using Startest I stumbled upon the need to assert that a string contains a substring, I've implemented a rather "abused" [function](https://github.com/patrik-kuehl/gleamyshell/blob/5855668e216649acdea26c86fa172099b8c1ef62/test/gleamyshell_test.gleam#L121C1-L137C2) since I didn't provide an alternative implementation for the `raise` and `show_diff` functions for better error reporting of this particular use case.

Are such assertions on the roadmap?

I'm unsure what approach would be the best fit here. Gleam doesn't support overloading functions so

```gleam
pub fn to_contain(does haystack: String, contains needle: String) -> Nil
pub fn to_contain(does haystack: List(value), contains needle: value) -> Nil
```

wouldn't be possible.

Using generics exclusively would require us to check the type via the `dynamic` module, a valid but cumbersome approach since such a function wouldn't tell its whole story via its signature (e.g., what happens when providing an unsupported type - requiring consumers to hope for the Hex documentation to cover such questions).

As of now, I'd favor implementing different functions per supported type like

```gleam
pub fn string_to_contain(does haystack: String, contains needle: String) -> Nil
pub fn list_to_contain(does haystack: List(value), contains needle: value) -> Nil
```

as it still results in a concise API that might look like this

```gleam
some_list
|> expect.list_to_contain(some_item)

some_string
|> expect.string_to_contain(some_substring)
```

eventually.

If help is accepted, I'm offering myself to contribute to this project, although I cannot make guarantees about how fast I can make such contributions because ... life and stuff^^

All the best.

**Comment by maxdeviant** [comment]
> Are such assertions on the roadmap?

Yes, I would love to eventually have a bunch of useful assertion functions 😄 

> As of now, I'd favor implementing different functions per supported type like
> 
> ```gleam
> pub fn string_to_contain(does haystack: String, contains needle: String) -> Nil
> pub fn list_to_contain(does haystack: List(value), contains needle: value) -> Nil
> ```

This is in line with what I was thinking as well. It seems very Gleam-y!

I just added a few new assertion functions to `main`:

- `expect/string_to_contain`
- `expect/string_to_start_with`
- `expect/string_to_end_with`
- `expect/list_to_contain`

They'll be available in the next version, which should be out in the next week or so.

**Comment by ghost** [comment]
That's great news, thanks for implementing them!

> They'll be available in the next version, which should be out in the next week or so.

Awesome, looking forward to replace my custom assertion with the new one when the next version is released.

I'll keep an eye out if I find more interesting use cases when using Startest in my projects.
