### ISSUE TITLE
Ability to filter down to test by given input

### ISSUE THREAD

**Issue by JosephTLyons** [maxdeviant/startest#21]
Using data-driven tests in `startest` is sweet, but it isn't trivial to debug a single test case when we run into some error in one test, amongst a see of generated tests. I have just been commenting out all the pieces of data generating tests when I want to put in debug code for the failing test. It would be awesome if `startest` had a flag for filtering down to just tests based on the given input.

A workflow I would like to have would be:

1. Run all data-driven tests
2. Hit an error with one
3. Filter down to just one test by using the input as a filter in a flag
4. Debug, fix the code, pass the test
5. Run all tests again without the input filter flag

**Comment by maxdeviant** [comment]
If you are embedding the inputs in the test names, then you should be able to use `--test-name-filter` to filter down to a particular test.

For instance, given this test: https://github.com/maxdeviant/startest/blob/aa35ccb7c8e34d25ce785ca53b93957b5d479426/test/example_project/describe_test.gleam#L6-L11

We could focus it by using `gleam test -- --test-name-filter="2 + 2"` or `gleam test -- --test-name-filter="2 + 2 ❯ = 4"`.

**Comment by JosephTLyons** [comment]
Makes sense!
